# Generated by Django 4.2.13 on 2024-05-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="message",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
